name: ArgomsCombat
main: com.argoms.argomscombat.ArgomsCombat
version: 0.2.8.1
description: >
             testing testing potato
commands:
  test:
    description: testing testing bread
  set:
    description: sets some crap